### ISSUE TITLE
New Release Request

### ISSUE THREAD

**Issue by mcharles-square** [bigcommerce/bigcommerce-api-node#31]
Hey team -

More endpoints have been since the last release 10 months ago. Any plans to cut a new release soon?

**Comment by bc-0dp** [comment]
The readme is not up to date with supported endpoints, so if you haven't already check here: https://github.com/bigcommerce/bigcommerce-api-node/tree/main/src/RestClient/endpoints

However, I believe there are initiatives in the works to auto generate the endpoints based on BC's OAS.

If there's anything concrete missing you need, I would recommend to add them yourself and create a PR 😄

**Comment by mcharles-square** [comment]
Thanks for the quick response @bc-0dp ! The api I need (`Customer`) is already implemented on `HEAD` :). The question was about releasing to **npm**. Sorry if not clear.

**Comment by bc-0dp** [comment]
Ahh my bad!
Yes, I agree.

@bc-nekisham 🚀

**Comment by mcharles-square** [comment]
Hi @bc-nekisham 👋 are you able to ship a release? 🙇

**Comment by bc-chaz** [comment]
@mcharles-square we will be updating this repo, and cutting a new release, shortly. We will address the errors caused by an update to one of the packages first, followed by a new release. We are targeting to have this done by early next month.

**Comment by MariaJose** [comment]
Hey @mcharles-square  👋🏼  FYI  new release has been made and the issue is resolved.
